#
#  appveyor.yml - Appveyor CI configuration for OWA EPANET
#
#  Date created: 01/09/2018
#
#  Author: Michael E. Tryby
#          US EPA - ORD/NRMRL
# 

version: 2.0.{build}

matrix: 
  allow_failures:
  #GROUP: (SUPPORTED/EXPERIMENTAL)
  #EXPERIMENTAL is allowed to fail under build matrix
  - GROUP: "EXPERIMENTAL"

environment: 
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    VS_VERSION: "10 2010"
    ARCH: Win32
    GROUP: "SUPPORTED"
    BOOST_ROOT:"C:/Libraries/boost"
    # New build on Visual Studio 15 2017
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    VS_VERSION: "15 2017"
    ARCH: Win64
    GROUP: "EXPERIMENTAL"
    BOOST_ROOT:"C:/Libraries/boost_1_67_0"

# called before repo cloning
init: 
  - set EPANET_HOME=%APPVEYOR_BUILD_FOLDER%
  - set BUILD_HOME=buildprod
  - set TEST_HOME=nrtestsuite
  - set NRTEST_SCRIPT=C:\Python27\Scripts
  - if "%ARCH%"=="Win64" (set VS_ARCH=Win64)
  - set GENERATOR="Visual Studio %VS_VERSION%%VS_ARCH%"
  # See values set
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - echo %ARCH%
  - echo %BUILD_HOME%
  - echo %GENERATOR%
  - echo %BOOST_ROOT%

# called after repo clone
install: 
  - python -m pip install -r tools\requirements-appveyor.txt

# called before build
before_build:
  - mkdir %BUILD_HOME%
  - cd %BUILD_HOME%
  - cmake -G %GENERATOR% 
    -DBOOST_ROOT="%BOOST_ROOT%"
    -DBoost_USE_STATIC_LIBS="ON" ..

# run custom build script
build_script: 
  - cmake --build . --config Release 

before_test:
  - cd %EPANET_HOME%
  - tools\before-test.cmd %TEST_HOME% %EPANET_HOME%\%BUILD_HOME%\bin\Release %APPVEYOR_REPO_COMMIT%

# run custom test script
test_script:
  # run unit tests
  - cd %BUILD_HOME%\tests
  - ctest -C Release
  # run regression tests
  - cd %EPANET_HOME%
  - tools\run-nrtest.cmd %NRTEST_SCRIPT% %TEST_HOME% %APPVEYOR_REPO_COMMIT%
