#
#  appveyor.yml - Appveyor CI configuration for OWA EPANET
#
#  Date created: 01/09/2018
#
#  Author: Michael E. Tryby
#          US EPA - ORD/NRMRL
# 

version: 2.0.{build} 

image: 
  - Visual Studio 2013

# called before repo cloning
init: 
  - set EPANET_HOME=%APPVEYOR_BUILD_FOLDER%
  - set BUILD_HOME=buildprod
  - set TEST_HOME=tests\epanet-nrtestsuite
  - set NRTEST_SCRIPT=%EPANET_HOME%\%BUILD_HOME%\packages\nrtest\scripts
  - set GENERATOR="Visual Studio 10 2010"

cache: 
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%BUILD_HOME% -> CMakeLists.txt'

# called after repo clone
install: 
  - choco install swig
  - python -m pip install --src %BUILD_HOME%\packages -r tools\requirements.txt

# called before build
before_build:
  - cd %BUILD_HOME%
  - cmake -G %GENERATOR% -D_CRT_SECURE_NO_DEPRECATE -DCMAKE_BUILD_TYPE=Release ..

# run custom build script
build_script: 
  - cmake --build . --target runepanet --config Release 

before_test:
  - cd %EPANET_HOME%
  - tools\gen-config.cmd %EPANET_HOME%\%BUILD_HOME%\bin\Release > %TEST_HOME%\apps\epanet-%APPVEYOR_REPO_COMMIT%.json 

# run custom test script
test_script:
  - tools\run-nrtest.cmd %NRTEST_SCRIPT% %TEST_HOME% %APPVEYOR_REPO_COMMIT%
